apiVersion: v1
kind: ConfigMap
metadata:
  name: security
  labels:
    {{- include "micro-security.labels" . | nindent 4 }}
data:
  application.yaml: |-
    database: mysql  
    spring:
      datasource:
        url: {{ .Values.db.url }}
        username: {{ .Values.db.username }}
        password: {{ .Values.db.password }}
        initialization-mode: always
      liquibase:
        enabled: true
        changeLog: classpath:/db/changelog/db.changelog-master.xml

    security:
      oauth2:
        client:
          clientId: security
          clientSecret: security_secret
          accessTokenUri: http://localhost:${PORT:80}/oauth/token
          grant-type: client_credentials
          scope: SERVICE

    logging:
      pattern:
        console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%t]){faint} %clr(%-40logger{39}){cyan}[%line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
      level:
        root: INFO

    server:
      port: ${PORT:80}
