#请在启动参数中加入--spring.profiles.active=mysql以激活本配置文件
database: payment

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/payment?useUnicode=true&characterEncoding=utf-8"
    username: root
    password: my-secret-pw
    initialization-mode: always
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/db.changelog-master.xml
  resources:
    chain:
      compressed: true
      cache: true
    cache:
      period: 86400

eureka:
  client:
    enabled: false
