Name:                   bookstore-microservices-domain-payment
Namespace:              bookstore-microservices
CreationTimestamp:      Sat, 16 Mar 2024 13:02:55 +0200
Labels:                 app=payment
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=payment
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=payment
  Service Account:  book-admin
  Containers:
   payment:
    Image:      icyfenix/bookstore-kubernetes-domain-payment
    Port:       80/TCP
    Host Port:  0/TCP
    Environment:
      PORT:               80
      JAVA_TOOL_OPTIONS:  -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
    Mounts:               <none>
  Volumes:                <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   bookstore-microservices-domain-payment-57b4bd9b65 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  12m   deployment-controller  Scaled up replica set bookstore-microservices-domain-payment-57b4bd9b65 to 1
