apiVersion: v1
data:
  spring.datasource.username: {{ .Values.db.username }}
  spring.datasource.password: {{ .Values.db.password }}
  spring.datasource.url: {{ .Values.db.url }}
kind: ConfigMap
metadata:
  name: {{ include "micro-account.fullname" . }}
  labels:
    {{- include "micro-account.labels" . | nindent 4 }}
