spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/warehouse?useUnicode=true&characterEncoding=utf-8"
    username: root
    password: my-secret-pw
    initialization-mode: always
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/db.changelog-master.xml