{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "micro-warehouse.serviceAccountName" . }}
  labels:
    {{- include "micro-warehouse.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}



#apiVersion: v1
#automountServiceAccountToken: true
#kind: ServiceAccount
#metadata:
#  annotations:
#    meta.helm.sh/release-name: micro-warehouse-1710670812
#    meta.helm.sh/release-namespace: default
#  creationTimestamp: "2024-03-17T10:20:16Z"
#  labels:
#    app.kubernetes.io/instance: micro-warehouse-1710670812
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/name: micro-warehouse
#    app.kubernetes.io/version: 1.16.0
#    helm.sh/chart: micro-warehouse-0.1.0
#  name: micro-warehouse-1710670812
#  namespace: default
#  resourceVersion: "1669649"
#  uid: 1c565246-4d22-4f2d-8d08-6c7659722131
